[package]
name = "wl-clipboard-watch"
version = "0.1.0"
edition = "2024"
description = "Watch Wayland clipboard selection changes"
repository = "https://github.com/so1ve/wl-clipboard-watch"
license = "MIT"
keywords = ["clipboard", "wayland"]
categories = ["os"]

[dependencies]
anyhow = "1.0.104"
rustix = { version = "1.1.4", features = ["event", "pipe", "time"] }
wayland-client = "0.31.15"
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }

[lints.clippy]
all = "warn"
clone_on_ref_ptr = "warn"
default_trait_access = "warn"
disallowed_methods = "warn"
enum_glob_use = "warn"
fn_params_excessive_bools = "warn"
format_collect = "warn"
format_push_string = "warn"
implicit_clone = "warn"
items_after_statements = "warn"
manual_let_else = "warn"
manual_string_new = "warn"
match_same_arms = "warn"
match_wildcard_for_single_variants = "warn"
missing_const_for_fn = "warn"
must_use_candidate = "warn"
needless_pass_by_value = "warn"
redundant_pub_crate = "warn"
semicolon_if_nothing_returned = "warn"
single_match_else = "warn"
struct_excessive_bools = "warn"
undocumented_unsafe_blocks = "warn"
uninlined_format_args = "warn"
unnecessary_literal_bound = "warn"
use_self = "warn"
verbose_file_reads = "warn"
wildcard_imports = "warn"
