name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rust:
    name: Rust
    uses: so1ve/workflows/.github/workflows/rust-ci.yml@v1
    with:
      toolchain: nightly
      runs-on: ubuntu-24.04
      runs-on-matrix: '"ubuntu-24.04"'
